// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2DTzoS2sM4ssLDckte_xJLqLRGQqXB4',
    appId: '1:327127186487:web:3ab03bb711f343ac4713b2',
    messagingSenderId: '327127186487',
    projectId: 'supply-chain-gen-man',
    authDomain: 'supply-chain-gen-man.firebaseapp.com',
    storageBucket: 'supply-chain-gen-man.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLtu5pNq1PpdaCEGqpaI11BA7TOqli80',
    appId: '1:327127186487:android:66116d0c82e22ac44713b2',
    messagingSenderId: '327127186487',
    projectId: 'supply-chain-gen-man',
    storageBucket: 'supply-chain-gen-man.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2DTzoS2sM4ssLDckte_xJLqLRGQqXB4',
    appId: '1:327127186487:web:93994059e9d6ada54713b2',
    messagingSenderId: '327127186487',
    projectId: 'supply-chain-gen-man',
    authDomain: 'supply-chain-gen-man.firebaseapp.com',
    storageBucket: 'supply-chain-gen-man.firebasestorage.app',
  );
}
